apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-api
  template:
    metadata:
      labels:
        app: calculator-api
    spec:
      containers:
        - name: calculator-api
          image: manjindersingh28/calculator-api:latest
          ports:
            - containerPort: 3040
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGODB_URI
          imagePullPolicy: Always
